services:
  productpage:
    build: .
    image: ghcr.io/iceevil4/bookinfo-productpage:dev
    ports:
      - "8083:8083"
    environment:
      RATINGS_HOSTNAME: http://ratings:8080
      DETAILS_HOSTNAME: http://details:8081
      REVIEWS_HOSTNAME: http://reviews:8082